### ISSUE TITLE
Picking Different Port Numbers

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Nodejs-Sia#15]
Looking through the code, it seems like only the default port numbers are allowed when starting 'siad'. There should be some option that allows you to start 'siad' on different ports. When setting up a developer network, each instance of siad needs its own port number for the api, the gateway rpcs, and the host rpcs.

**Comment by Mingling94** [comment]
How do I start siad on a different port? CL arguments? Pointing me to documentation would be fine enough.

**Comment by DavidVorick** [comment]
`siad -h`
