### ISSUE TITLE
Remove download functionality

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Nodejs-Sia#21]
The ability to download Sia releases seems out-of-scope for this package.
More pressingly, the dependencies required (tar and unzip) are pulling in a deeply nested node_modules tree, which makes Sia-UI a pain to install on Windows due to the "path too long" bug.
Removing download functionality would solve the problem, but it would be just as well to find some way of pruning the dependency tree of Sia-UI.
(npm claims to keep the tree flat, but I haven't observed that behavior in practice.)

**Comment by Mingling94** [comment]
Note that TravisCI depends on downloading siad to test the UI since it would not have siad to begin with (though it's not verified that siad actually runs on TravisCI).

**Comment by DavidVorick** [comment]
That's no reason to have the functionality appear in our releases.

I'm in general against being able to download 'siad' from the UI, It should come pre-packaged, and that's it. Updating can be done by each internally and separately.

**Comment by Mingling94** [comment]
I don't understand your last sentence. If you remove the functionality from siad, the UI's .travis.yml could just execute something to download siad to the Travis server instead.
