### ISSUE TITLE
Blocking caused by setImmediate

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Nodejs-Sia#22]
In sia.js there is the following comment:

``` js
    // TODO: Don't understand why the setImmediate is needed, but without it,
    // some calls seems to not return right after another call but eventually
    // do return once another call is made. Some sort of resource blocking is
    // happnening
    setImmediate(function () {
      apiCall.apply(this, args)
    })
```

However, in my tests I have found the opposite to be true. Normally, there is about a 1-in-10 chance that when you load Sia-UI, the values displayed in the Overview will be uninitialized, and only load after the next update. When I removed the call to `setImmediate`, I was not able to reproduce this scenario; the values always updated immediately upon load.

**Comment by lukechampine** [comment]
hmm. Further testing shows that the blocking behavior can still occur without `setImmediate` (not in Overview, but a different plugin). Clearly this warrants more investigation.

**Comment by lukechampine** [comment]
why do you need to call `apiCall.apply(this, args)` anyway? `apiCall` doesn't seem to require `this`.

**Comment by Mingling94** [comment]
Oh yeah, `this` could be null.

**Comment by lukechampine** [comment]
Further investigation: `Siad.configure` may be causing the problem. When I removed the call to `Siad.configure` (called during initialization of most plugins), I was unable to reproduce the issue.
`Siad.configure` makes an API call, and does so without the use of `setImmediate`. My guess is that this is somehow causing the IO blockage.

**Comment by Mingling94** [comment]
Ah, then you could edit `apiCall()` itself to use `setImmediate()`. That's probably better than having `SiadWrapper.call()` be an alias

**Comment by lukechampine** [comment]
resolved by https://github.com/NebulousLabs/Nodejs-Sia/commit/529c4f5fda53752d7c7a6f17553ca2bc3a505f4a and https://github.com/NebulousLabs/Nodejs-Sia/commit/8fb20cab3781a04940e25bb9c164838d475ffb5e
